Repository melanieloredo/game-4, pull requests merged in 2025-04, with the labels that each got.

#14 Fixing button bug in game
  game-4.gba
  src/game_scene.cpp
  src/main.cpp
Labels: bug

#15 Refactor (merge button-fix first)
  game-4.gba
  include/game_scene.h
  include/room1.h
  include/room2.h
  src/game_scene.cpp
  src/main.cpp
  src/room_1.cpp
  src/room_2.cpp
  src/titlescreen.cpp
Labels: documentation, enhancement

#16 changed y camera borders (merge refactor first)
  game-4.gba
  include/camera.h
Labels: bug

#23 room2 added to the asset folder
  game-4.gba
  graphics/room2_bg.bmp
  graphics/room2_bg.json
Labels: art

#31 Room2 and hearts completed
  graphics/heart.bmp
  graphics/heart.json
  graphics/room2_bg.bmp
  src/main.cpp
Labels: art
